#k8-manifests\service\nodeport-svc.yml
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  labels:
    stackroute-k8: nodeport-svc
spec:
  type: NodePort
  selector:
    stackroute-k8: nginx
  ports:
   - nodePort: 31000
     port: 80
     targetPort: 80
    
  